-*- coding: utf-8 -*-
"""microMedGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hnueyGh9GmefrxYk_NSsvVLFI5YFd7F
"""

# Commented out IPython magic to ensure Python compatibility.
# --------------------
# Install tokenizer library and tensorboard
# --------------------

!pip install tokenizers
!pip install tensorboard

# --------------------
# Imports
# --------------------

import os
import re
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.nn import functional as F
from tokenizers import ByteLevelBPETokenizer
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("runs/microMedGPT")

# --------------------
# Hyperparameters
# --------------------

batch_size = 16
block_size = 32  # number of tokens
max_iters = 2000
eval_interval = 100
learning_rate = 1e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0


# --------------------
# Checkpoint paths
# --------------------

checkpoint_dir = "checkpoints"
os.makedirs(checkpoint_dir, exist_ok=True)

model_ckpt = os.path.join(checkpoint_dir, "microMedGPT_model.pt")
tokenizer_ckpt = os.path.join(checkpoint_dir, "medical_tokenizer.json")

torch.manual_seed(167)


# --------------------
# Load dataset
# --------------------

file_path = 'microMedGPT.txt'

# Upload file if not present (Colab)
if not os.path.exists(file_path):
    try:
        from google.colab import files
        uploaded = files.upload()
        for name in uploaded.keys():
            file_path = name
    except ImportError:
        raise FileNotFoundError(f"{file_path} not found and not running in Colab.")

# Read raw text
with open(file_path, 'r', encoding='utf-8') as f:
    raw_text = f.read()


# --------------------
# Expanded preprocessing
# --------------------

# Allowed characters
allowed_chars = (
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "0123456789.,:;!?()/- \n%"
)
special_tokens = ["<note>", "<SEP>", "<report>"]

# Abbreviation + lab expansion
abbreviation_map = {
    "fbg": "fasting blood glucose",
    "hba1c": "hemoglobin a1c",
    "pt": "patient",
    "wt": "weight",
    "rul": "right upper lobe",
    "lul": "left upper lobe",
    "ll": "left lower lobe",
    "rl": "right lower lobe",
    "ct": "computed tomography",
    "mri": "magnetic resonance imaging",
    "bp": "blood pressure",
    "hr": "heart rate",
    "rr": "respiratory rate",
    "c/o": "complains of",
    "hx": "history",
    "dm": "diabetes mellitus",
    "htn": "hypertension",
    "cad": "coronary artery disease",
    "mi": "myocardial infarction",
    "copd": "chronic obstructive pulmonary disease",
    "sob": "shortness of breath",
    "npo": "nothing by mouth",
    "po": "by mouth",
    "iv": "intravenous",
    "q": "every",
    "tid": "three times a day",
    "bid": "twice a day",
    "prn": "as needed",
    "stat": "immediately",
    "o2": "oxygen",
    # Lab abbreviations / units
    "mg/dl": "milligrams per deciliter",
    "mmhg": "millimeters of mercury",
    "bpm": "beats per minute",
    "l": "liter",
    "kg": "kilogram",
    "cm": "centimeter",
    # add more as needed (see if necessary)
}

# Expand abbreviations
def expand_abbreviations(text, abbr_map):
    text = text.lower()  # lowercase first
    for abbr, full in abbr_map.items():
        text = re.sub(rf"\b{re.escape(abbr)}\b", full, text)
    return text

# Normalize numbers with units (optional, more consistent)
def normalize_units(text):
    # Examples: 210 mg/dL -> 210 milligrams per deciliter
    text = re.sub(r"(\d+)\s*mg/dl", r"\1 milligrams per deciliter", text)
    text = re.sub(r"(\d+)\s*mmhg", r"\1 millimeters of mercury", text)
    text = re.sub(r"(\d+)\s*kg", r"\1 kilograms", text)
    text = re.sub(r"(\d+)\s*cm", r"\1 centimeters", text)
    return text

# Clean text while preserving special tokens
def clean_text(text):
    for token in special_tokens:
        text = text.replace(token, f" {token} ")
    # Remove unwanted characters
    text = re.sub(f"[^{re.escape(allowed_chars)}]", " ", text)
    # Replace multiple spaces with one
    text = re.sub("\s+", " ", text)
    return text.strip()

# Apply full pipeline
cleaned_text = clean_text(raw_text)
cleaned_text = expand_abbreviations(cleaned_text, abbreviation_map)
cleaned_text = normalize_units(cleaned_text)

print(f"Loaded, cleaned, and fully standardized dataset: {len(cleaned_text)} characters")


# --------------------
# Train or load tokenizer
# --------------------

tokenizer_file = "medical_tokenizer.json"

if not os.path.exists(tokenizer_file):
    print("Training new tokenizer...")

    # Create a temporary file with the cleaned text for training
    temp_file = "temp_training_data.txt"
    with open(temp_file, 'w', encoding='utf-8') as f:
        f.write(cleaned_text)

    # Initialize tokenizer
    tokenizer = ByteLevelBPETokenizer()

    # Train tokenizer on the temporary file
    tokenizer.train(
        files=[temp_file],
        vocab_size=5000,
        min_frequency=2,
        special_tokens=["<PAD>", "<UNK>", "<SEP>", "<note>", "<report>"]
    )

    # Save tokenizer
    tokenizer.save_model(".", "medical_tokenizer")

    # Clean up temporary file
    os.remove(temp_file)

    print("Tokenizer training completed.")
else:
    print("Loading existing tokenizer...")
    # Load existing tokenizer
    tokenizer = ByteLevelBPETokenizer("medical_tokenizer-vocab.json", "medical_tokenizer-merges.txt")

# Encode cleaned text
print("Encoding text...")
encoded_result = tokenizer.encode(cleaned_text)
data = torch.tensor(encoded_result.ids, dtype=torch.long)

print(f"Length of cleaned_text: {len(cleaned_text)}")
print(f"Length of encoded data tensor: {len(data)}")

# Get vocabulary size
vocab_size = tokenizer.get_vocab_size()
print("Vocab size:", vocab_size)

# Verify tokenizer is working
if vocab_size == 0 or len(data) == 0:
    raise ValueError("Tokenizer failed to initialize properly. Check your input data.")

# Define encode/decode functions
encode = lambda s: tokenizer.encode(s).ids
decode = lambda l: tokenizer.decode(l)


# --------------------
# Prepare dataset
# --------------------

# Use the data tensor created from encoding cleaned_text
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

print(f"Train data length: {len(train_data)}")
print(f"Validation data length: {len(val_data)}")


# --------------------
# Auto-adjust block_size and batch_size
# --------------------

min_split_len = min(len(train_data), len(val_data))
if min_split_len == 0:
    raise ValueError("Training or validation data is empty after tokenization.")

# Ensure we have enough data for the block size
if block_size >= min_split_len:
    old_block = block_size
    block_size = max(4, min_split_len // 2)  # at least 4, but leave room for sequences
    print(f"⚠️ block_size {old_block} too large for dataset ({min_split_len} tokens). Reduced to {block_size}.")

# Ensure we have enough data for the batch size
max_possible_batch = min_split_len - block_size
if batch_size > max_possible_batch:
    old_batch = batch_size
    batch_size = max(1, max_possible_batch)
    print(f"⚠️ batch_size {old_batch} too large for dataset. Reduced to {batch_size}.")

print(f"Final block_size: {block_size}")
print(f"Final batch_size: {batch_size}")

def sample_batch(split):
    data_split = train_data if split == 'train' else val_data
    if len(data_split) <= block_size:
        raise ValueError(
            f"Split '{split}' too small: {len(data_split)} tokens for block_size={block_size}."
        )
    ix = torch.randint(len(data_split) - block_size, (batch_size,))
    x = torch.stack([data_split[i:i + block_size] for i in ix])
    y = torch.stack([data_split[i + 1:i + block_size + 1] for i in ix])
    return x.to(device), y.to(device)

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = sample_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out


# --------------------
# Model components
# --------------------

class AttentionHead(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2, -1) * C ** -0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([AttentionHead(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))

class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class TransformerBlock(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


# --------------------
# Helper function for advanced sampling
# --------------------

@torch.no_grad()
def sample_next_token(logits, temperature=1.0, top_k=None, top_p=None):
    """
    logits: tensor of shape (B, vocab_size) for the current time step
    temperature: float, >0, higher values = more random
    top_k: int, keep only top-k tokens
    top_p: float in (0,1], keep smallest set of tokens with cumulative probability >= top_p
    """
    if temperature != 1.0:
        logits = logits / temperature

    probs = F.softmax(logits, dim=-1)

    if top_k is not None:
        top_probs, top_idx = probs.topk(top_k)
        mask = torch.zeros_like(probs).scatter_(1, top_idx, top_probs)
        probs = mask / mask.sum(dim=-1, keepdim=True)

    if top_p is not None:
        sorted_probs, sorted_idx = torch.sort(probs, descending=True)
        cumulative_probs = torch.cumsum(sorted_probs, dim=-1)
        mask = cumulative_probs > top_p
        mask[:, 0] = False  # always keep the top token
        sorted_probs[mask] = 0
        probs = torch.zeros_like(probs).scatter_(1, sorted_idx, sorted_probs)
        probs = probs / probs.sum(dim=-1, keepdim=True)

    next_token = torch.multinomial(probs, num_samples=1)
    return next_token


# --------------------
# Conditional GPT model
# --------------------

class MicroMedGPTModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[TransformerBlock(n_embd, n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, idx, max_new_tokens, sep_token="<SEP>", temperature=1.0, top_k=None, top_p=None):
        """
        idx: (B, T) tensor of input tokens (notes + <SEP>)
        Returns the generated report text only.
        """
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :]
            idx_next = sample_next_token(logits, temperature=temperature, top_k=top_k, top_p=top_p)
            idx = torch.cat((idx, idx_next), dim=1)

        decoded = decode(idx[0].tolist())
        if sep_token in decoded:
            return decoded.split(sep_token)[-1].strip()
        else:
           return decoded


# ----------------------------------
# Wrapper function for multiple generations
# ----------------------------------

def generate_reports(model, notes, max_tokens=200, n=3, temperature=1.0, top_k=None, top_p=None, stop_tokens=None):
    stop_tokens = stop_tokens or ["<report>", "---"]
    context = torch.tensor([encode(notes)], dtype=torch.long, device=device)
    outputs = []

    for _ in range(n):
        gen_text = model.generate(
            context,
            max_new_tokens=max_tokens,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p
        )
        for stop_token in stop_tokens:
            if stop_token in gen_text:
                gen_text = gen_text.split(stop_token)[0].strip()
        outputs.append(gen_text)

    return outputs


# --------------------
# Initialize model & optimizer
# --------------------

model = MicroMedGPTModel().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

# Add learning rate scheduler
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_iters)

print(f"{sum(p.numel() for p in model.parameters())/1e6:.2f}M parameters")


# --------------------
# Lists to track training progress
# --------------------

train_losses = []
val_losses = []
eval_iterations = []  # Track which iterations we evaluated at
learning_rates = []
grad_norms = []


# --------------------
# Training loop
# --------------------

for iter in range(max_iters):
    # Evaluate losses every eval_interval steps
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        train_loss = losses['train'].item()
        val_loss = losses['val'].item()
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        eval_iterations.append(iter)  # Track the actual iteration number
        print(f"Step {iter}: train loss {train_loss:.4f}, val loss {val_loss:.4f}")

        # Log to TensorBoard
        writer.add_scalar('Loss/train', train_loss, iter)
        writer.add_scalar('Loss/val', val_loss, iter)

    xb, yb = sample_batch('train')
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()


    # compute gradient norm before clipping
    total_norm = 0
    for p in model.parameters():
        if p.grad is not None:
            param_norm = p.grad.data.norm(2)
            total_norm += param_norm.item() ** 2
    total_norm = total_norm ** 0.5
    writer.add_scalar("GradNorm/total", total_norm, iter)
    grad_norms.append(total_norm)


    # gradient clipping
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

    optimizer.step()
    scheduler.step()   # update the learning rate

    # log current learning rate every iteration
    current_lr = scheduler.get_last_lr()[0]
    writer.add_scalar('LearningRate', current_lr, iter)
    learning_rates.append(current_lr)  # store for matplotlib plotting


# --------------------
# Save final model + tokenizer
# --------------------

torch.save(model.state_dict(), model_ckpt)
print(f"Model saved to {model_ckpt}")
print(f"Tokenizer files saved in current directory")


# --------------------
# Plot training & validation loss
# --------------------

plt.figure(figsize=(8, 5))
plt.plot(eval_iterations, train_losses, label='Train Loss')
plt.plot(eval_iterations, val_losses, label='Validation Loss')
plt.xlabel('Iteration')
plt.ylabel('Loss')
plt.title('Training & Validation Loss')
plt.legend()
plt.show()


# --------------------
# Plot learning rate schedule
# --------------------

plt.figure(figsize=(8, 5))
plt.plot(range(max_iters), learning_rates, label='Learning Rate')
plt.xlabel('Iteration')
plt.ylabel('LR')
plt.title('Learning Rate Schedule (Cosine Annealing)')
plt.legend()
plt.show()


# --------------------
# Plot gradient norms
# --------------------

plt.figure(figsize=(8, 5))
plt.plot(range(len(grad_norms)), grad_norms, label='Gradient Norm')
plt.axhline(y=1.0, color='r', linestyle='--', label='Clipping Threshold')
plt.xlabel('Iteration')
plt.ylabel('Gradient Norm')
plt.title('Gradient Norms During Training')
plt.legend()
plt.show()


# --------------------
# Launch TensorBoard
# --------------------

# %load_ext tensorboard
# %tensorboard --logdir runs


# --------------------
# Generate multiple reports using wrapper
# --------------------

example_notes = "F 45 yo, polyuria, polydipsia. FBG 210 mg/dL, HbA1c 8.5%. <SEP>"

# Generate 3 variations of the report
reports = generate_reports(
    model,
    example_notes,
    max_tokens=200,       # maximum number of tokens to generate
    n=3,                  # generate 3 different reports
    temperature=0.8,      # adjust randomness
    top_k=50,             # top-k sampling
    top_p=0.9,            # top-p sampling
    stop_tokens=["<report>"]  # stop when these tokens appear
)

# Print each generated report
for i, r in enumerate(reports, 1):
    print(f"Report {i}:\n{r}\n{'-'*50}")